Public Class AllAccountInfo
    Private Sub AllAccountInfo_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        If Manager.NameTxt.Text = "John Smith" Then
            lstInfo.Items.Add("Name: John Smith")
            lstInfo.Items.Add("Age: 38")
            lstInfo.Items.Add("Address: 99 Wall St., New York, NY 10005")
            lstInfo.Items.Add("IP Address: 99.999.999.99")
            lstInfo.Items.Add("Last Deposit Date: 2 Apr. 2019")
            lstInfo.Items.Add("Deposit Amount: $50,000")
            lstInfo.Items.Add("Last Withdrawal Date: 26 Apr. 2019")
            lstInfo.Items.Add("Withdrawal Amount: $100,000")
            lstInfo.Items.Add("Account Savings: $942,368")
        ElseIf Manager.NameTxt.Text = "Ophelia Tellerson" Then
            lstInfo.Items.Add("Name: Ophelia Tellerson")
            lstInfo.Items.Add("Age: 23")
            lstInfo.Items.Add("Address: Somehwere, Pacific Ocean, A Mile Below Surface")
            lstInfo.Items.Add("IP Address: Somewhere")
            lstInfo.Items.Add("Last Deposit Date: 6 May 2018")
            lstInfo.Items.Add("Deposit Amount: $600,000")
            lstInfo.Items.Add("Last Withdrawal Date: 9 Jan. 2017")
            lstInfo.Items.Add("Withdrawal Amount: $57,512")
            lstInfo.Items.Add("Account Savings: $987,465")
        ElseIf Manager.NameTxt.Text = "Hamish Tiller" Then
            lstInfo.Items.Add("Name: Hamish Tiller")
            lstInfo.Items.Add("Age: 36")
            lstInfo.Items.Add("Address: Antartica")
            lstInfo.Items.Add("IP Address: Somewhere")
            lstInfo.Items.Add("Last Deposit Date: 8 Dec. 2013")
            lstInfo.Items.Add("Deposit Amount: $56,152")
            lstInfo.Items.Add("Last Withdrawal Date: 11 Aug. 2018")
            lstInfo.Items.Add("Withdrawal Amount: $38,417")
            lstInfo.Items.Add("Account Savings: $157,860")
        ElseIf Manager.NameTxt.Text = "Nathan Tiller" Then
            lstInfo.Items.Add("Name: Hamish Tiller")
            lstInfo.Items.Add("Age: 31")
            lstInfo.Items.Add("Address: Too Lazy")
            lstInfo.Items.Add("IP Address: Somewhere")
            lstInfo.Items.Add("Last Deposit Date: 8 Dec. 2013")
            lstInfo.Items.Add("Deposit Amount: $56,152")
            lstInfo.Items.Add("Last Withdrawal Date: 11 Aug. 2018")
            lstInfo.Items.Add("Withdrawal Amount: $38,417")
            lstInfo.Items.Add("Account Savings: $157,860")
        ElseIf Manager.NameTxt.Text = "Carl Timpson" Then
            lstInfo.Items.Add("Name: Carl Timpson")
            lstInfo.Items.Add("Age: 39")
            lstInfo.Items.Add("Address: Too Lazy")
            lstInfo.Items.Add("IP Address: Somewhere")
            lstInfo.Items.Add("Last Deposit Date: 8 Dec. 2013")
            lstInfo.Items.Add("Deposit Amount: $56,152")
            lstInfo.Items.Add("Last Withdrawal Date: 11 Aug. 2018")
            lstInfo.Items.Add("Withdrawal Amount: $38,417")
            lstInfo.Items.Add("Account Savings: $157,860")
        ElseIf Manager.NameTxt.Text = "Earl Timpson" Then
            lstInfo.Items.Add("Name: Earl Timpson")
            lstInfo.Items.Add("Age: 26")
            lstInfo.Items.Add("Address: Too Lazy")
            lstInfo.Items.Add("IP Address: Somewhere")
            lstInfo.Items.Add("Last Deposit Date: 8 Dec. 2013")
            lstInfo.Items.Add("Deposit Amount: $56,152")
            lstInfo.Items.Add("Last Withdrawal Date: 11 Aug. 2018")
            lstInfo.Items.Add("Withdrawal Amount: $38,417")
            lstInfo.Items.Add("Account Savings: $157,860")
        ElseIf Manager.NameTxt.Text = "Napoleon Timpson" Then
            lstInfo.Items.Add("Name: Napoleon Timpson")
            lstInfo.Items.Add("Age: 18")
            lstInfo.Items.Add("Address: Too Lazy")
            lstInfo.Items.Add("IP Address: Somewhere")
            lstInfo.Items.Add("Last Deposit Date: 8 Dec. 2013")
            lstInfo.Items.Add("Deposit Amount: $56,152")
            lstInfo.Items.Add("Last Withdrawal Date: 11 Aug. 2018")
            lstInfo.Items.Add("Withdrawal Amount: $38,417")
            lstInfo.Items.Add("Account Savings: $157,860")
        ElseIf Manager.NameTxt.Text = "Anonymous Trader" Then
            lstInfo.Items.Add("Name: Anonymous Trader")
            lstInfo.Items.Add("Age: ??")
            lstInfo.Items.Add("Address: Jupiter")
            lstInfo.Items.Add("IP Address: ??.???.???.??")
            lstInfo.Items.Add("Last Deposit Date: 36 Dec. 2511")
            lstInfo.Items.Add("Deposit Amount: $???,???,???,???")
            lstInfo.Items.Add("Last Withdrawal Date: 78 Jan. 2512")
            lstInfo.Items.Add("Withdrawal Amount: $???,???,???,???,???")
            lstInfo.Items.Add("Account Savings: $1,150,168,145,126")
        End If
    End Sub

    Private Sub OKBtn_Click(sender As Object, e As EventArgs) Handles OKBtn.Click
        Me.Close()
    End Sub
End Class
